name: Build Production & Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize Submodules
        run: git submodule update --init Firmware/Embedded-Sharepoint

      - name: Cache Nix
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install Nix Action
        uses: cachix/install-nix-action@v31

      - name: Test Production Build
        run: |
          nix develop ./Firmware/Embedded-Sharepoint --accept-flake-config --command bash -c "
            cd Firmware/ && make clean && make
          "
      - name: Clean & Build tests
        run: |
          nix develop ./Firmware/Embedded-Sharepoint --accept-flake-config --command bash -c "
            cd Firmware/Embedded-Sharepoint && make clean && python tests/makeAllTests.py
          "